### ISSUE TITLE
When going up from Rides page, the songs page launches instead of the front page

### ISSUE THREAD

**Issue by ghost** [ischeinkman/OfficialRamonApp#23]
Doesn't matter what page you come from. Possible fix:

public void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        getActionBar().setDisplayHomeAsUpEnabled(true);
    }
    @Override
    public boolean onOptionsItemSelected(MenuItem item){
        switch(item.getItemId()){
            case android.R.id.home:
                Intent changeActivity = new Intent(this, FrontalActivity.class);
                startActivity(changeActivity);
                return true;
              /\*  finish();
                return true; */
        }
        return super.onOptionsItemSelected(item);
    }

But now I am going to sleep. I will fix this tomorrow.

**Comment by ischeinkman** [comment]
1. Grab a parent activity intent instead of a hardcoded FrontalActivity intent.
2. Why finish() the activity?
3. It apparently already does go back to the FrontalActivity on up navigation, it simply opens the wrong fragment. Manually recreating the intent should not change this. Something else is causing the issue.
