### ISSUE TITLE
Automatically calculate rides

### ISSUE THREAD

**Issue by ischeinkman** [ischeinkman/OfficialRamonApp#31]

**Comment by ischeinkman** [comment]
Possible v1 implementation: 
--Create list of "areas" with defined center points and 2-d coordinate values
--On aleph/driver add, calculate distances from defined centers using a mapping API (Google?)
--Aleph/driver is set as in the area with the shortest distance.
--User can set if only fills free space or completely empties drivers
--On algorithm run, the app iterates over the drivers. 
--For each driver iterates over the alephs.
--Adds alephs with the lowest area distances (distance formula on area coords)

**Comment by ofekih** [comment]
Suggestion:
1) Go driver by driver to add any Alephs that are significantly closer to them than other drivers.
2) Go driver by driver to add Alephs that are closer to them than other drivers if they have space.
3) Leave 'bitch rides' open for drivers to manually chose

**Comment by ofekih** [comment]
Actually, a one-for-one app wouldn't be too beneficial, since maybe some drivers are hanging out, or some are limited by this that or the other. The best thing to do would be some kind of visual indication of where the drivers are located, and where the Alephs are located and have the metaksher decide. So maybe put blue pins on a map where drivers are located, and green pins where Alephs are located. Having the computer match automatically is simply not beneficial.

**Comment by ischeinkman** [comment]
Hangouts would be inputted before the algorithm is run, and then the user can select to only fill free space. 
While you may not see the benefit of this feature, it has been heavily requested by many users, even if it is far from perfect. Manually matching rides, even with a good-looking interface, is tedious, and users would rather edit a generated list than create a new one.

**Comment by ofekih** [comment]
Go ahead, but note some things.

Those who have requested this feature fail to see its flaws.

It will take a whole lot of time to input the variables. A list of
variables I can already see you will need include the number of people each
driver can take, which isn't that difficult of a task, and hangouts. Keep
in mind their may be multiple hangouts going on, but I will get more into
that in the special cases section.

However the amount of cases you will overlook is the amount you have
implemented + 1, and that will stay constant no matter how many cases you
have implemented. Here is a list of cases I can think of off the top of my
head. Many of these cases could result in a need to completely redo rides
(pretty tedious), and will ultimately make using such an application much
more pain than it's worth. Keep in mind that for every case I can think of,
there are three more I haven't that would similarly result in a complete
redo of rides. You can ask any metaksher for more special cases that proved
to be a pain in the butt.
1. One hangout becomes two different hangouts
2. An Aleph or Alephs can't hangout because their mom is pissed.
3. A driver has curfew and an Aleph wants to stay till the end.
4. There aren't enough rides
5. Several Alephs are sleeping over
6. Alephs / drivers come late to an event
7. A person came with a bike so the corresponding driver has less room
   in his car
8. A driver promised an Aleph a ride home / are friends and want to go
   home together
9. A driver isn't willing to drive so far
10. The algorithm calculated rides poorly for at least one driver and
    the driver complains.
11. Parents are helping with rides :O

Of course, some of these can be fixed with a paper and pencil easily, but
they won't be given a paper and pencil; yet an phone (where things aren't
so malleable). Of course they could copy by hand from the calculated rides
(that might not even come up with a solution, or come up with a completely
non-helpful solution as many perfect computer solutions are), but copying
by hand takes away the whole point of the app.

That was the in short list of flaws I could find out. Note that for a map
to simply show blue and orange pins signifying Alephs and drivers the
metaksher simply needs to go down the list of Alephs in the phone list and
check off the Alephs as either driving or at the event, and then
immediately see a visual representation that can be easily changed as
people come and go. After spending around 2 minutes at most doing this,
they would start their normal pencil and paper technique (and there's a
reason every single chapter in the order uses it) and would be able to very
quickly finish rides.

You can go ahead with the algorithm, just be warned (that it won't help as
you think it will).

On Mon, Aug 24, 2015 at 6:35 PM, ischeinkman notifications@github.com
wrote:

> Hangouts would be inputted before the algorithm is run, and then the user
> can select to only fill free space.
> While you may not see the benefit of this feature, it has been heavily
> requested by many users, even if it is far from perfect. Manually matching
> rides, even with a good-looking interface, is tedious, and users would
> rather edit a generated list than create a new one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ischeinkman/OfficialRamonApp/issues/31#issuecomment-134439907
> .

## 

Ofek Gila

**Comment by ischeinkman** [comment]
The rides list is editable in-app both before and after the algorithm is run, and again can be set to only fill free space.
However you did raise a good point of hangouts, namely that some will ONLY take hangouts. This might mean that we will need to include per-driver algorithmic exclusions as well.
Again, this was never meant to completely REPLACE rides, only create a rough draft to start with, so that the rides maker is only editing and not replacing a list.
